# Generated by Django 6.1.1 on 2026-09-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True, help_text='OPIS Truckstop ID — primary business key from the source CSV.', unique=True)),
                ('name', models.CharField(help_text='Truckstop name.', max_length=255)),
                ('address', models.CharField(help_text='Raw address string as it appears in the CSV.', max_length=512)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(help_text='Two-character US state code.', max_length=2)),
                ('rack_id', models.IntegerField(help_text='Rack ID from the CSV — a pricing zone identifier.')),
                ('price', models.DecimalField(decimal_places=8, help_text='Retail fuel price in USD per gallon.', max_digits=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='WGS-84 latitude (city centroid from Nominatim).', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='WGS-84 longitude (city centroid from Nominatim).', max_digits=9, null=True)),
                ('geocoded_at', models.DateTimeField(blank=True, help_text='Timestamp of the last successful geocoding for this station.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fuel Station',
                'verbose_name_plural': 'Fuel Stations',
                'indexes': [models.Index(fields=['city', 'state'], name='idx_station_city_state'), models.Index(fields=['latitude', 'longitude'], name='idx_station_coords')],
            },
        ),
    ]
